core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views#this is imported to make the user authenticatoin 
from  .forms import login_form#this is imported to make the data that is requires to input from the user in the forms .py of this aopp to verify the data where login_form is the class to make the uuser input the authentication crecentials

app_name="core"
urlpattern=[
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path("signup/",views.signup , name="signup"),
    path("login/" , auth_views.LoginView.as_view(template_name="core/login.html" , authentication_form=login_form), name="login"),
]

skills/urls.py
from django.urls import path
from . import views
app_name="skills"
urlpatterns=[
    path("<int:pk>/", views.detail , name="detail"),
    path("", views.skills ,  name="skills"),
    path("create/", views.create ,  name="create"),
    path("<int:pk>/delete/", views.delete, name="delete"),
    path("<int:pk>/edit/", views.edit, name="edit"),

]

xetsef/urls.py
from django.contrib import admin
from django.urls import path , include
from core.views import index,contact
from django.conf import settings
from django.conf.urls.static import static
 
'''admin.site.site_header="Xetsef Administration"
admin.site.site_title="Xetsef Admin Portal"
admin.site.index_title="Xetsef"'''
urlpatterns = [
    path("", include('core.urls')),
    path("skills/", include("skills.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("inbox/", include("inbox.urls")),
    path('sp524074', admin.site.urls),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm#imports the authentication form and the user creation form to verify the existance of the user and to create a user
from django.contrib.auth.models import User
class login_form(AuthenticationForm):
    User_name=forms.CharField(widget=forms.TextInput(attrs={
        "placeholder" : "Enter your user name",
        "class" : "w-full py-6 rounded-xl"#this is a html code for the creation of  the look of the login box tyope to authenticate and to create the users                                                            
    }))
    passwords= forms.Charfield(widget= forms.PasswordInput(attr={
        "placeholder" : "Enter your password",#make the user to input the password in the placeholder
        "class" : "w-full py-4 px-6 rounded-xl" #this is a html code for the creation of  the look of the login box tyope to authenticate and to create the users
    }))
class signup_form(UserCreationForm):
    class Meta:
        model = User
        fields = ("user_name" , "email" , "password1" , "password2" )
    user_name = forms.CharField(widget=forms.TextInput(attrs={#this is the constraint used to create the user name of the client side server
        "placeholder" : "Enter your name",
        "class" :"w-full py-4 px-6 rounded-xl"
    }))
    email= forms.CharField(widget=forms.Emailinput(attrs={
        "placeholder": "enter your email",
        "class"  : "w-full py-4 px-6 rounded-xl"
    }))
    password1= forms.CharField(widget = forms.PasswordInput(attrs={
        "placeholder" : "enter your password",
        "class" : "w-full py-4 px-6 rounded-xl"
    }))
    password2= forms.CharField(widget = forms.PasswordInput(attrs={
        "placeholder" :"repeat the pasword that you entered earlier",
        "class" : "w-full py-4 px--6 rounded-xl"
    }))

core/views.py
from django.shortcuts import render , redirect
from skills.models import category, data
from .forms import signup_form#import the data of the signup_forms class from the forms.py
def index(request):
    skills=data.objects.filter(is_sold=False)#shiw the items that we added to the index of the hom page
    categories=category.objects.all()

    return render(request,'core/index.html',{
        "categories" : categories,
        "skills": skills,

    })
def contact(request):
    return render(request,'core/contact.html')
def signup(request):
    if request.method == "POST":
        form = signup_form(request.POST)#here the signup_form is used to take the dat from the forms.py files where data is stores in the clas signup_form class
        if form.is_valid():
            form.save()#this is to save the form data
            return redirect("/login/")#make the user to redirect to the login page for the purpose of login after the cration of the account is succesfully completed
    else:
        form =signup_form()
    return render(request , "core/signup.html",{#here the return functio is used to return the page to the signup form
        "form" :form
        })
# Create your views here.

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://cdn.tailwindcss.com"></script>
        <title>{% block title%} {% endblock title%} | xetsef</title>
    </head>
    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-5xl font-semibold"> Xetsef</a>
                <div class="space-x-6">
                    <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>
                    <a href="#" class="text-lg font-semibold hover:text-gray-500">Skills</a>
                    <a href="#" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                    <a href="#" class="px-6 py-3 text-lg font-semi-bold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log In</a>

                </div>
            </nav>

        <div class="px-6 py-6">
            {% block body%}
            {%endblock body%}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">

                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">hruhrgtjfuhfgerfh erferberuff er fuukendjkwerhor efhfhfr wff\rfrfgheg  \rfrehfer er erferfmerf erverfer]ferfer  werjhwer9ur34nmf erfnfrg </p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu></h3>
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url "core:contact" %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy Policy of Use</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Terms and conditions</a></li>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends "core/base.html" %}
{%block title%} Contact Us
{% endblock title %}
{% block body %}
this is the conatct page
{% endblock body %}

core/templates/core/index.html
{% extends "core/base.html" %}
{%block title%} Home
{% endblock title %}
{% block body %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Mentors</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for users in category %}

        <div>
            <a href="{% url "skills:detail" data.id %}">
                <div> 
                    <img src="{{user.user_images.url}}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-cl">
                    <h2 class="text-2xl">{{data.user}}</h2>
                    <p class="text-gray-500">Price:{{data.price}}</p>
                </div>
            </a>
        </div>

        {% endfor %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Categories</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
            <div>
                <a href="#">
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500"> {{ category.users.count }} items</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock body %}

core/templates/core/login.html
{% extends "core/base.html" %}
{%block title%}Log in{%endblock%}
{%block content%}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblocK %} 